title: "Containerisation & DevOps - Ananya Karn"
description: "Course experiments and project assignments"
theme: jekyll-theme-cayman
baseurl: "/containerisation-devOps-AnanyaKarn-500125205-B3-ccvt"
url: "https://kripinya.github.io"

include:
  - "Project-Assignment-1"

exclude:
  - "Dockerfile"
  - "docker-compose.yml"
  - "network_setup.sh"
  - "*.sh"
  - "node_modules"
  - "my-flask-app"
  - "sapid-checker"
  - ".gitignore"
